#!/usr/bin/env python3.8

raise ValueError("A fake error")
